version: "3.8"
services:
  api:
    build: ./RocketFitBackend_Python/RocketFitDjango2
    container_name: api_rf
    ports:
      - "8000:8080"
    # command: python3 manage.py runserver 
  application:
    build: ./rocket-fit-front/client
    container_name: app_rf
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true